name: Deploy Serverless Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Must match the region in your main.tf

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 4. Initialize Terraform
      # This step MUST be told where the terraform files are.
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # 5. Apply Terraform changes automatically
      # This step also needs to be in the correct directory.
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
