name: Deploy Serverless Backend to AWS

# Run this workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Define the working directory as the terraform folder
    defaults:
      run:
        working-directory: ./terraform

    steps:
      # 1. Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Must match the region in your main.tf

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Apply Terraform changes automatically
      - name: Terraform Apply
        run: terraform apply -auto-approve
